server {
    listen 8080;

    root /usr/share/nginx/html;
    index index.html;

    # SPA fallback: cualquier ruta de Angular cae a index.html
    location / {
    try_files $uri $uri/ /index.html;
    }

    location /api/bonos {
        proxy_pass ${BONOS_SERVICE_URL};
    }
    location /api/apuestas {
        proxy_pass ${APUESTAS_SERVICE_URL};
    }
    location /api/estadisticas {
        proxy_pass ${ESTADISTICAS_SERVICE_URL};
    }

    # Reverse proxy al backend en subred privada
    location /api/ {
    proxy_pass ${BACKEND_URL};
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Cache de assets estáticos
    location ~* \.(?:js|css|woff2?|svg|png|jpg|jpeg|gif|ico)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    }
}